name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install "numpy==1.26.4" "pandas==2.2.2"

      - name: Import analytics and run a tiny check
        run: |
          python - << 'PY'
          import pandas as pd
          from analytics import zscore_anomalies
          s = pd.Series([10,10,10,50], dtype="float")
          out = zscore_anomalies(s, threshold=2.0)
          assert out.iloc[-1] and not out.iloc[0]
          print("CI OK ✅")
          PY
